### ISSUE TITLE
How to compiling the buildroot for 2d01?

### ISSUE THREAD

**Issue by tonyho** [fifteenhex/buildroot_idosom2d01#1]
Thanks for the great job.
How can I compile the rescue and rich rootfs? 
I clone this repo, then `git submodule update --init` to clone the submodules, then I use `make` to compiling, it hints:

```
Makefile:951: *** Please configure Buildroot first (e.g. "make menuconfig").  Stop.
Makefile:84: recipe for target '_all' failed
make[1]: *** [_all] Error 2
br2secretsauce/common.mk:35: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2
```

Any hints?

**Comment by fifteenhex** [comment]
Hi,

You should be able to checkout, run "make bootstrap" and then run "make". You have to do it all in the root directory of the checkout.

**Comment by tonyho** [comment]
> Hi,
> 
> You should be able to checkout, run "make bootstrap" and then run "make". You have to do it all in the root directory of the checkout.

Thanks for the reply, it still has error:
```
make 
mkdir -p /home/Projects/SigmaStar202/buildroot_idosom2d01/outputs
mkdir -p /home//Projects/SigmaStar202/buildroot_idosom2d01/dl
make -s -C buildroot BR2_DL_DIR=/home/Projects/SigmaStar202/buildroot_idosom2d01/dl BR2_EXTERNAL="../br2autosshkey ../br2idosom2d01" BR2_DEFCONFIG="../br2idosom2d01/configs/idosom2d01_defconfig"
Makefile:951: *** Please configure Buildroot first (e.g. "make menuconfig").  Stop.
Makefile:84: recipe for target '_all' failed
make[1]: *** [_all] Error 2
br2secretsauce/common.mk:60: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2

```

**Comment by tonyho** [comment]
> Hi,
> 
> Can you try pulling master, make sure the modules update, and try again? I think I fixed that.

Thanks for the reply and fix, now I can build and get the artifacts.


Only some warnings still here:
```
make bootstrap
Makefile:19: br2secretsauce/common.mk: No such file or directory
Makefile:20: br2secretsauce/rescue.mk: No such file or directory
```

**Comment by tonyho** [comment]
Artifacts got verified.
