### ISSUE TITLE
Git procedures conflict?

### ISSUE THREAD

**Issue by ltrsunny** [fifteenhex/buildroot_idosom2d01#10]
I tried 
`make buildroot-linux-menuconfig`
it pulled the codes and I edited the config.

Then I `make` it, but it seems repulling and overwrite the previous one. 

```
>>> linux-headers mstar_v5_16_rebase Downloading
error: RPC failed; curl 16 Error in the HTTP2 framing layer
fatal: expected flush after ref listing
Detected a corrupted git cache.
Removing it and starting afresh.
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
remote: Enumerating objects: 8493235, done.
remote: Counting objects: 100% (2037/2037), done.
remote: Compressing objects: 100% (1348/1348), done.
Receiving objects:   2% (178877/8493235), 89.67 MiB | 42.00 KiB/s
```

**Comment by ltrsunny** [comment]
```
GIT_DIR=/home/dev/buildroot_idosom2d01/dl/linux/git/.git git fetch origin -t
remote: Enumerating objects: 4648, done.
remote: Counting objects: 100% (136/136), done.
remote: Total 4648 (delta 136), reused 136 (delta 136), pack-reused 4512
Receiving objects: 100% (4648/4648), 20.91 MiB | 11.77 MiB/s, done.
Resolving deltas: 100% (320/320), completed with 74 local objects.
From https://github.com/linux-chenxing/linux
 * [new tag]                   mstar-5.14   -> mstar-5.14
 * [new tag]                   v2.6.11      -> v2.6.11
 * [new tag]                   v2.6.11-tree -> v2.6.11-tree
Could not fetch special ref 'mstar_v5_16_rebase'; assuming it is not special.
Commit 'mstar_v5_16_rebase' does not exist in this repository.
wget --passive-ftp -nd -t 3 -O '/home/dev/buildroot_idosom2d01/buildroot/output/build/.linux-mstar_v5_16_rebase-br1.tar.gz.sGyn0x/output' 'http://sources.buildroot.net/linux/linux-mstar_v5_16_rebase-br1.tar.gz'
--2021-12-12 00:50:40--  http://sources.buildroot.net/linux/linux-mstar_v5_16_rebase-br1.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 172.67.72.56, 104.26.0.37, 104.26.1.37, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|172.67.72.56|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-12 00:50:41 ERROR 404: Not Found.

wget --passive-ftp -nd -t 3 -O '/home/dev/buildroot_idosom2d01/buildroot/output/build/.linux-mstar_v5_16_rebase-br1.tar.gz.0560o5/output' 'http://sources.buildroot.net/linux-mstar_v5_16_rebase-br1.tar.gz'
--2021-12-12 00:50:41--  http://sources.buildroot.net/linux-mstar_v5_16_rebase-br1.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37, 172.67.72.56, 104.26.1.37, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-12 00:50:41 ERROR 404: Not Found.

```

It is tring to get “http://sources.buildroot.net/linux-mstar_v5_16_rebase-br1.tar.gz” but nothing available there.

**Comment by fifteenhex** [comment]
mm thats very weird. Try downloading the files in dl/linux and see if it can download them again.

**Comment by ltrsunny** [comment]
> mm thats very weird. Try downloading the files in dl/linux and see if it can download them again.

It will reinitialize the git status and repeat from very beginning I give it a loop to make until it succeeds. But my connection is not that stable, hope it can be done tomorrow…….

BTW I tried menuconfig again, my settings still there, lucky in the misfortune😂

**Comment by ltrsunny** [comment]
I think I got the point, 
It is trying to get `http://sources.buildroot.net/uboot/uboot-mstar_rebase_mainline-br1.tar.gz`
but nothing available there.

**Comment by fifteenhex** [comment]
> It seems trying to get `http://sources.buildroot.net/uboot/uboot-mstar_rebase_mainline-br1.tar.gz` but nothing available there.

buildroot will do that if it fails to pull from git. But as u-boot and the kernel are not available from the buildroot mirrors it will fail.
I'll try to work out a solution for this. If your connection to github isn't good you're going to get stuck.

**Comment by ltrsunny** [comment]
> > It seems trying to get `http://sources.buildroot.net/uboot/uboot-mstar_rebase_mainline-br1.tar.gz` but nothing available there.
> 
> buildroot will do that if it fails to pull from git. But as u-boot and the kernel are not available from the buildroot mirrors it will fail. I'll try to work out a solution for this. If your connection to github isn't good you're going to get stuck.

My connection to Github is... random? I guess it would be better in early morning, maybe.

**Comment by ninoslavb** [comment]
> > It seems trying to get `http://sources.buildroot.net/uboot/uboot-mstar_rebase_mainline-br1.tar.gz` but nothing available there.
> 
> buildroot will do that if it fails to pull from git. But as u-boot and the kernel are not available from the buildroot mirrors it will fail. I'll try to work out a solution for this. If your connection to github isn't good you're going to get stuck.

Have you found the solution for this?
