### ISSUE TITLE
How to re-burn the official SPL and bootloader?

### ISSUE THREAD

**Issue by tonyho** [fifteenhex/buildroot_idosom2d01#4]
Hi I'm back again.
There's an error if I use SPI burn tool to re-burn the official uboot/SPL after the new version/upstream uboot has been burned:

![Upstream_revert_SPINotFound_Burn](https://user-images.githubusercontent.com/2195048/140024477-4a6ee3af-55fe-43a9-8034-70398b88ac7b.png)

Do we have to erase the uboot at new uboot before use the SPI burnning tool?

I use the `spi erase` to erase in new uboot command line, and it failed:
```
=> sf protect unlock 0 1000
=> sf erase 0 10000        
ERROR: attempting erase past flash size (0x38)
=> 

```

Any tips? Thanks.

**Comment by ddB0515** [comment]
I had same error but not caused by UART it was already booted so you need to restart in uBoot and send `debug`
![image](https://user-images.githubusercontent.com/20762436/141696516-da9f71c3-32f2-4b8d-b51e-d2e4133682eb.png)

after that you can connect via I2C ISP tool and do all operation normally
